### ISSUE TITLE
@grd cannot generate normal .grd file

### ISSUE THREAD

**Issue by mastreina** [Rasic2/gvasp#3]
when using @grd function generating vasp.grd files, gvasp returns with a .grd file with an all 0 file. 
Path:
@(134 server): /data/home/xgong/xyzhang/co2+h/stm-h-o-recheck-bader

**Comment by Rasic2** [comment]
The grd task use a DenCut to control the cutoff density and its default value is 250, which may be not suitable for your system. 

You can close the DenCut option by using the command:

```
gvasp grd -d -1
```
or set a DenCut a positive integer (you can try it by yourself).

```
gvasp grd -d NUM
```

**Comment by grd** [comment]
What is this? Why are you mentioning me?

**Comment by Rasic2** [comment]
> 

Sorry, he makes a mistake by adding a "@" symbol on "grd" text
