### ISSUE TITLE
About the visualization process

### ISSUE THREAD

**Issue by RedStar-Iron** [Rasic2/gvasp#9]
Hi, 

Just a quick question.

Does this project transfer some of the output files of VASP to the .arc files that can be read by MS, then we use MS to visualize these files? Or, this project supply a `GUI` which can visualize the output files directly on the Linux system?

Thanks

**Comment by Rasic2** [comment]
Thanks for your question. You're right that this tool doesn't supply a GUI but transform the output files of VASP to a .arc file.
